### ISSUE TITLE
Null ref exception

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin-plugin-tvmaze#1]
```
[20:17:01] [WRN] [12] Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider: [GetMetadata]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.TvMaze.Providers.TvHelpers.GetStrippedHtml(String input)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider.GetMetadataInternal(EpisodeInfo info)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
```

**Comment by crobibero** [comment]
```
[2020-11-08 20:56:25.817 -07:00] [INF] [32] Jellyfin.Plugin.TvMaze.Providers.TvMazeSeriesImageProvider: [GetImages] Images found for "A Discovery of Witches": [RemoteImageInfo { ProviderName: "TV Maze", Url: "http://static.tvmaze.com/uploads/images/original_untouched/176/441320.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }]
[2020-11-08 20:56:26.305 -07:00] [WRN] [32] Jellyfin.Plugin.TvMaze.Providers.TvMazeSeasonProvider: [GetMetadata]
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.DateTime'. Path '[2].endDate', line 1, position 1126.
 ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TvMaze.Api.Client.Extensions.HttpClientExtensions.GetAsync[T](HttpClient httpClient, String url)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeSeasonProvider.GetSeasonInternal(SeasonInfo info)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeSeasonProvider.GetMetadata(SeasonInfo info, CancellationToken cancellationToken)
[2020-11-08 20:56:26.495 -07:00] [WRN] [32] Jellyfin.Plugin.TvMaze.Providers.TvMazeSeasonImageProvider: [GetImages]
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.DateTime'. Path '[2].endDate', line 1, position 1126.
 ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TvMaze.Api.Client.Extensions.HttpClientExtensions.GetAsync[T](HttpClient httpClient, String url)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeSeasonImageProvider.GetSeasonImagesInternal(IHasProviderIds series, Int32 seasonNumber)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
```
